CREATE SEQUENCE REVIEW_REPLY_SEQ;

CREATE TABLE REVIEW_REPLY(
	review_reply_num NUMBER(10),
	review_idx NUMBER(10),
	u_id VARCHAR2(100),
	review_reply_content VARCHAR2(4000),
	CONSTRAINT REVIEW_REPLY_PK PRIMARY KEY(review_reply_num),
	CONSTRAINT REPLY_REVIEW_FK FOREIGN KEY(review_idx) REFERENCES REVIEW(review_idx),
	CONSTRAINT REPLY_USER_FK FOREIGN KEY(u_id) REFERENCES USER_PROFILE(u_id)
);

/*ALTER TABLE REVIEW_REPLY DROP CONSTRAINT REPLY_REVIEW_FK;

/*부모가 삭제되면 자식도 삭제되도록 실행
ALTER TABLE REVIEW_REPLY ADD CONSTRAINT REPLY_REVIEW_FK 
FOREIGN KEY(review_idx) REFERENCES REVIEW(review_idx)
ON DELETE CASCADE;*/

SELECT * FROM REVIEW_REPLY;

INSERT INTO REVIEW_REPLY (REVIEW_REPLY_NUM, review_idx, u_id, REVIEW_REPLY_CONTENT) 
VALUES (REVIEW_REPLY_SEQ.NEXTVAL, 28, 'hds9638', '저도 써보고 싶네요');

/*DELETE FROM TABLE_BOARD WHERE BOARD_NUM = 22;*/