CREATE SEQUENCE REVIEW_SEQ;

CREATE TABLE REVIEW(
	review_idx	NUMBER(10),
	review_title VARCHAR2(1000),
	review_content VARCHAR2(3000),
	review_id	VARCHAR2(100),
	review_date	DATE,
	CONSTRAINT REVIEW_PK PRIMARY KEY (review_idx),
	CONSTRAINT REVIEW_FK FOREIGN KEY (review_id) REFERENCEs USER_PROFILE(u_id)
);
SELECT * FROM REVIEW;
SELECT REVIEW_IDX FROM REVIEW;
/*DROP TABLE POST;
DROP SEQUENCE POST_SEQ;*/
INSERT INTO REVIEW
VALUES(REVIEW_SEQ.NEXTVAL, '테스트 제목11', '테스트 내용11', 'hds9638', SYSDATE);
/*
SELECT ROWNUM,T.*FROM(SELECT*FROM POST P ORDER BY 1 DESC) T;*/
SELECT * FROM	
			(SELECT ROWNUM R, D.* FROM
				(SELECT * FROM REVIEW ORDER BY review_idx DESC) D) B;
SELECT * FROM 	
 			(SELECT ROWNUM R, D.* FROM
				(SELECT * FROM REVIEW ORDER BY review_idx DESC) D) B 
 		WHERE B.R BETWEEN ${startRow} AND ${endRow} ;
 	
/*SELECT * FROM REVIEW WHERE REVIEW_IDX = 42;*/

CREATE TABLE REVIEW_FILES(
	r_file_name VARCHAR2(100),
	review_idx NUMBER(10),
	CONSTRAINT REVIEW_FILES_PK PRIMARY KEY(r_file_name),
	CONSTRAINT REVIEW_FILES_FK FOREIGN KEY(review_idx) REFERENCES REVIEW(review_idx)
);
SELECT * FROM REVIEW_FILES WHERE REVIEW_IDX = 61;
SELECT * FROM REVIEW_FILES;
